### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'flickr_bert_text_embed.npz'

### ISSUE THREAD

**Issue by lan41981** [princetonvisualai/multimodal_dataset_distillation#1]
In buffer.py, there is a line of code on line 39: data = np.load(f'{args.dataset}_{args.text_encoder}_text_embed. 
The error message is as follows: Traceback (most recent call last)
File "/root/autodl-tmp/multi/buffer.py", line 168, in
main(args)
File "/root/autodl-tmp/multi/buffer.py", line 39, in main
data = np.load(f'{args.dataset}_{args.text_encoder}_text_embed.npz')
The File "/ root/miniconda3 / envs/distillation/lib/python3.9 / site - packages/numpy/lib/npyio. Py", line 417, in the load
fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'flickr_bert_text_embed.npz'
Where can I download "flickr_bert_text_embed.npz"?

**Comment by nightrain-vampire** [comment]
> In buffer.py, there is a line of code on line 39: data = np.load(f'{args.dataset}_{args.text_encoder}_text_embed. The error message is as follows: Traceback (most recent call last) File "/root/autodl-tmp/multi/buffer.py", line 168, in main(args) File "/root/autodl-tmp/multi/buffer.py", line 39, in main data = np.load(f'{args.dataset}_{args.text_encoder}_text_embed.npz') The File "/ root/miniconda3 / envs/distillation/lib/python3.9 / site - packages/numpy/lib/npyio. Py", line 417, in the load fid = stack.enter_context(open(os_fspath(file), "rb")) FileNotFoundError: [Errno 2] No such file or directory: 'flickr_bert_text_embed.npz' Where can I download "flickr_bert_text_embed.npz"?

I also encountered the same problem. I used the COCO dataset, and the error message was: FileNotFoundError:[Errno 2] No such file or directory: 'coco_bert_text_embed.npz'. Have you solved this problem now?

**Comment by XindiWu** [comment]
Hi, 

I have updated the code to address this issue. Now, you can directly generate the required .npz files using the `load_or_process_file` function. This update should help in creating files like flickr_bert_text_embed.npz and others that were previously missing. Please pull the latest changes from the repository and let me know if you have any other questions:)
